// golem-website/src/components/Footer.vue
<!--
  This example requires Tailwind CSS v2.0+ 
  
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ]
  }
  ```
-->
<template>
  <footer class="bg-white" aria-labelledby="footer-heading">
    <h2 id="footer-heading" class="sr-only">Footer</h2>
    <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
      <div class="xl:grid xl:grid-cols-3 xl:gap-8">
        <div class="grid grid-cols-3 gap-8 xl:col-span-3">
          <div class="md:grid md:grid-cols-2 md:gap-8">
            <div>
              <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                Products
              </h3>
              <ul class="mt-4 space-y-4">
                <li v-for="item in navigation.Products" :key="item.name">
                  <a :href="item.href" class="text-base text-gray-500 hover:text-gray-900">
                    {{ item.name }}
                  </a>
                </li>
              </ul>
            </div>
            <div class="mt-12 md:mt-0">
              <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                Developers
              </h3>
              <ul class="mt-4 space-y-4">
                <li v-for="item in navigation.Developers" :key="item.name">
                  <a :href="item.href" class="text-base text-gray-500 hover:text-gray-900">
                    {{ item.name }}
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="md:grid md:grid-cols-2 md:gap-8">
            <div>
              <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                Community
              </h3>
              <ul class="mt-4 space-y-4">
                <li v-for="item in navigation.Community" :key="item.name">
                  <a :href="item.href" class="text-base text-gray-500 hover:text-gray-900">
                    {{ item.name }}
                  </a>
                </li>
              </ul>
            </div>
            <div class="mt-12 md:mt-0">
              <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                GLM
              </h3>
              <ul class="mt-4 space-y-4">
                <li v-for="item in navigation.GLM" :key="item.name">
                  <a :href="item.href" class="text-base text-gray-500 hover:text-gray-900">
                    {{ item.name }}
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="md:grid md:grid-cols-2 md:gap-8">
            <div>
              <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                Resources
              </h3>
              <ul class="mt-4 space-y-4">
                <li v-for="item in navigation.Resources" :key="item.name">
                  <a :href="item.href" class="text-base text-gray-500 hover:text-gray-900">
                    {{ item.name }}
                  </a>
                </li>
              </ul>
            </div>
            <div class="mt-12 md:mt-0">
              <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                About
              </h3>
              <ul class="mt-4 space-y-4">
                <li v-for="item in navigation.About" :key="item.name">
                  <a :href="item.href" class="text-base text-gray-500 hover:text-gray-900">
                    {{ item.name }}
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="mt-8 border-t border-gray-200 pt-8 md:flex md:items-center md:justify-between">
        <div class="mt-8 xl:mt-0">
          <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
            Subscribe to our newsletter
          </h3>
          <p class="mt-4 text-base text-gray-500">
            The latest news, articles, and resources, sent to your inbox weekly.
          </p>
          <form class="mt-4 sm:flex sm:max-w-md">
            <label for="email-address" class="sr-only">Email address</label>
            <input
              type="email"
              name="email-address"
              id="email-address"
              autocomplete="email"
              required=""
              class="appearance-none min-w-0 w-full bg-white border border-gray-300 rounded-md shadow-sm py-2 px-4 text-base text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:placeholder-gray-400"
              placeholder="Enter your email"
            />
            <div class="mt-3 rounded-md sm:mt-0 sm:ml-3 sm:flex-shrink-0">
              <button
                type="submit"
                class="w-full bg-golemblue flex items-center justify-center border border-transparent rounded-md py-2 px-4 text-base font-medium text-white hover:bg-indigo-400 focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Subscribe
              </button>
            </div>
          </form>
        </div>
        <div class="flex space-x-6 md:order-2">
          <a v-for="item in navigation.social" :key="item.name" :href="item.href" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">{{ item.name }}</span>
            <component :is="item.icon" class="h-6 w-6" aria-hidden="true" />
          </a>
          <img class="h-6 w-6 text-white" src="https://discord.com/assets/2d20a45d79110dc5bf947137e9d99b66.svg" />
        </div>
        <p class="mt-8 text-base text-gray-400 md:mt-0 md:order-1">
          &copy; 2021 Golem Factory GmbH, Inc. All rights reserved.
        </p>
      </div>
    </div>
  </footer>
</template>

<script>
import { defineComponent, h } from "vue"

const navigation = {
  Products: [
    { name: "Platform", href: "#" },
    { name: "Become a Provider", href: "#" },
    { name: "Network Stats", href: "#" },
    { name: "Graphene", href: "#" },
  ],
  Developers: [
    { name: "SDK", href: "#" },
    { name: "Requestor Docs", href: "#" },
    { name: "Test Harness", href: "#" },
    { name: "Github", href: "#" },
  ],
  Community: [
    { name: "Featured Projects", href: "#" },
    { name: "Awesome Golem", href: "#" },
    { name: "GLM-Rewards", href: "#" },
    { name: "Upcoming Events", href: "#" },
    { name: "Blog", href: "#" },
  ],
  GLM: [
    { name: "About the token", href: "#" },
    { name: "Migration", href: "#" },
  ],
  Resources: [
    { name: "Privacy Policy", href: "#" },
    { name: "UiG", href: "#" },
    { name: "Disclaimer", href: "#" },
    { name: "Whitepaper", href: "#" },
    { name: "Brand assets", href: "#" },
  ],
  About: [
    { name: "Overview", href: "#" },
    { name: "Team", href: "#" },
    { name: "Contact", href: "#" },
  ],
  social: [
    {
      name: "Facebook",
      href: "#",
      icon: defineComponent({
        render: () =>
          h("svg", { fill: "currentColor", viewBox: "0 0 24 24" }, [
            h("path", {
              "fill-rule": "evenodd",
              d:
                "M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z",
              "clip-rule": "evenodd",
            }),
          ]),
      }),
    },
    {
      name: "Instagram",
      href: "#",
      icon: defineComponent({
        render: () =>
          h("svg", { fill: "currentColor", viewBox: "0 0 24 24" }, [
            h("path", {
              "fill-rule": "evenodd",
              d:
                "M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z",
              "clip-rule": "evenodd",
            }),
          ]),
      }),
    },
    {
      name: "Twitter",
      href: "#",
      icon: defineComponent({
        render: () =>
          h("svg", { fill: "currentColor", viewBox: "0 0 24 24" }, [
            h("path", {
              d:
                "M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84",
            }),
          ]),
      }),
    },
    {
      name: "GitHub",
      href: "#",
      icon: defineComponent({
        render: () =>
          h("svg", { fill: "currentColor", viewBox: "0 0 24 24" }, [
            h("path", {
              "fill-rule": "evenodd",
              d:
                "M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z",
              "clip-rule": "evenodd",
            }),
          ]),
      }),
    },
  ],
}

export default {
  setup() {
    return {
      navigation,
    }
  },
}
</script>

// components/Footer.jsx
export default function Footer() {
    return (
        <section className="bg-white z-10 pb-20 relative border-t">
            <div className="pt-24 mx-auto max-w-7xl px-4 sm:px-6  w-full ">
                <div className="grid grid-cols-12 lg:gap-x-10 gap-x-0">
                    <div className="lg:col-span-4 col-span-12 text-center lg:text-left mb-10 lg:mb-0">
                        <h4 className="text-golemblue  text-2xl  font-semibold">Golem Network</h4>
                        <div className="mt-4 sm:max-w-lg sm:mx-auto sm:text-center lg:text-left lg:mx-0">
                            <p className="text-base mb-2font-medium text-gray-900">Sign up to our newsletter.</p>
                            <form action="#" method="POST" className="mt-3 sm:flex">
                                <label htmlFor="email" className="sr-only">
                                    Email
                                </label>
                                <input
                                    type="email"
                                    name="email"
                                    id="email"
                                    className="appearance-none min-w-0 w-full bg-white border border-gray-300 rounded-md shadow-sm py-2 px-4 text-base mb-2text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:placeholder-gray-400"
                                    placeholder="Enter your email"
                                />
                                <button
                                    type="submit"
                                    className="mt-3 w-full px-6 py-3 border border-transparent text-base mb-2font-medium rounded-md text-white bg-golemblue shadow-sm hover:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:flex-shrink-0 sm:inline-flex sm:items-center sm:w-auto"
                                >
                                    Subscribe
                                </button>
                            </form>
                            <p className="mt-3 text-sm text-gray-500">
                                We care about the protection of your data. Read our
                                <a href="#" className="font-medium ml-1 text-gray-900 underline">
                                    Privacy Policy
                                </a>
                                .
                            </p>
                        </div>
                    </div>
                    <div className="lg:col-span-8 col-span-12 grid grid-cols-12 text-center lg:text-left  gap-y-10">
                        <div className="lg:col-span-3 col-span-6">
                            <p className="text-base mb-2">Products</p>
                            <a className="text-gray-500 text-sm leading-7 block ">Platform</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Become a provider</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Stats</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Graphene</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Clay Golem</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Golem Unlimited</a>
                        </div>
                        <div className="lg:col-span-3 col-span-6 ">
                            <p className="text-base mb-2">Developers</p>
                            <a className="text-gray-500 text-sm leading-6 block  ">SDK</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Requestor Docs</a>
                            <p className="text-gray-500 text-sm leading-6 block  ">Test Harness</p>
                            <p className="text-gray-500 text-sm leading-6 block  ">Github</p>
                        </div>
                        <div className="lg:col-span-3 col-span-6">
                            <p className="text-base mb-2">Community</p>
                            <a className="text-gray-500 text-sm leading-6 block  ">Featured Projects</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Awesome Golem</a>
                            <p className="text-gray-500 text-sm leading-6 block  ">GLM Rewards</p>
                            <p className="text-gray-500 text-sm leading-6 block  ">Upcoming Events</p>
                            <p className="text-gray-500 text-sm leading-6 block  ">Blog</p>
                        </div>
                        <div className="lg:col-span-3 col-span-6">
                            <p className="text-base mb-2">GLM</p>
                            <a className="text-gray-500 text-sm leading-6 block  ">About the token</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Migration</a>
                        </div>
                        <div className="lg:col-span-3 col-span-6">
                            <p className="text-base mb-2">Resources</p>
                            <a className="text-gray-500 text-sm leading-6 block  ">Privacy Policy</a>
                            <a className="text-gray-500 text-sm leading-6 block ">UiG</a>
                            <p className="text-gray-500 text-sm leading-6 block  ">Disclaimer</p>
                            <p className="text-gray-500 text-sm leading-6 block  ">Whitepaper</p>
                            <p className="text-gray-500 text-sm leading-6 block  ">Brand Assets</p>
                        </div>
                        <div className="lg:col-span-3 col-span-6">
                            <p className="text-base mb-2">About</p>
                            <a className="text-gray-500 text-sm leading-6 block  ">Overview</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Team</a>
                            <p className="text-gray-500 text-sm leading-6 block  ">Contact</p>
                        </div>
                        <div className="lg:col-span-3 col-span-6">
                            <p className="text-base mb-2">Get Started</p>
                            <a className="text-gray-500 text-sm leading-6 block  ">Provider Tutorial</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Requestor Tutorial</a>
                        </div>
                        <div className="lg:col-span-3 col-span-6">
                            <p className="text-base mb-2">Socials</p>
                            <a className="text-gray-500 text-sm leading-6 block  ">Discord</a>
                            <a className="text-gray-500 text-sm leading-6 block ">Twitter</a>
                            <p className="text-gray-500 text-sm leading-6 block  ">Telegram</p>
                        </div>
                    </div>
                    <div className="col-span-12 border-t mt-10"></div>
                    <div className="col-span-12 grid grid-cols-12 py-12 gap-y-2 lg:gap-y-0">
                        <div className="lg:col-span-3 col-span-12 text-gray-700 text-center lg:text-left">© 2022 Golem Factory Gmbh.</div>
                        <div className="lg:col-span-6 col-span-12 grid grid-cols-12 text-center">
                            <div className="lg:col-span-4 col-span-12">Brand Policy</div>
                            <div className="lg:col-span-4 col-span-12">Privacy Policy</div>
                            <div className="lg:col-span-4 col-span-12">Terms of Service</div>
                        </div>
                        <div className="text-center col-span-12 lg:col-span-1 lg:text-right">Logos</div>
                    </div>
                </div>
            </div>
        </section>
    )
}
